### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by matiaswp** [johannaspo/elokuvakerho#1]
Moi!

Kokeilin sovellusta herokussa ja se pelittää mainiosti. Toiminnot näyttää toimivan kuten niiden pitääkin muutamaa pientä asiaa lukuunottamatta, joista mainitsen alempana. Sovelluksen rakenne on selkeä ja sitä on helppoa käyttää. Mielestäni sovelluksen toteutusta voisi parantaa mahdollisesti seuraavilla tavoilla:

+ Jaa sovelluksen koodi pienempiin tiedostoihin. Tämä näyttääkin olevan jo sinulla TODO-listassa.
+ Nyt admin voi lisätä jäsenen, jonka tunnukset ovat esimerkiksi pelkkiä space-merkkejä. Kannattaa korjata. 
+ Myös elokuvan, jonka nimessä on pelkkiä space-merkkejä, pystytään luomaan. Kannattaa tämäkin korjata.
+ Pitkät koodirivit kannattaa lyhentää jakamalla ne useammalle riville. Näin on jossain kohdissa tehty, mutta ei kaikkialla.  
(https://hy-tsoha.github.io/materiaali/pages/ohjelmointityyli.html kohta 8).

Ylllä olevia asioita lukuunottamatta työ näyttää erittäin hyvältä ja toimii tosi hyvin.

**Comment by johannaspo** [comment]
Kiitos hyvistä kommenteista!
