### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by Jarkkorm** [johannaspo/elokuvakerho#2]
Vaikuttaa hyvältä. Toiminnallisuudet ja ulkonäkö ovat toimivia.
Arvostelun jälkeen jää näkyviin arvostelu kaavake kunnes tajuaa rullata alemmas.
Suunnitellut toimenpiteet vielä kuntoon niin on täydellinen.

**Comment by johannaspo** [comment]
Kiitos arvioinnista!
